"""Added category, shelf and task models

Revision ID: 42647f455c0b
Revises: bb4af8b66269
Create Date: 2025-03-23 14:58:43.970806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42647f455c0b'
down_revision = 'bb4af8b66269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.alter_column('shelf_id',
               existing_type=sa.String(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_photo_shelf', 'shelf', ['shelf_id'], ['id'])

    with op.batch_alter_table('planogram', schema=None) as batch_op:
        batch_op.alter_column('shelf_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_photo_shelf_id', 'shelf', ['shelf_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planogram', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('shelf_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('shelf_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
